language: python
python:
- '2.7'
addons:
  apt:
    packages:
      - pandoc
install: pip install -r requirements-dev.txt
script: nosetests
deploy:
  - provider: pypi
    server: https://testpypi.python.org/pypi
    user: rjosephwright
    password:
      secure: soLkjlD9D91shjcAGft76lE5Qc/njNzLnvQ+4H1s6KtXgTPDoWQih6EGbPdijGJjH5FnDmplB697z4GmVZRbjIvljYXb2+eQqwxQ+G0VXt147uBwF97PPE1jCUAQMB55QaMZuCp/QDVFqP9yGkQNgGCDdiVGq/khxW0W1mP65loJG+/T0CZZLQP83d7CX5qUH2/3wIbzhzTUdSqesxA+OmBLbly3r+Xw/+2u5XajCK5CRZ7oLiGBP9HnO8EEVipnfJDjsj7aYOKn0DYMGmumzr71EyVhAN40E+7QhE6of+oAVgMUi30jx+kmr37SHSEKpv8mRr6DwY8lar54+k/AQCD0aQpfgdjaHGk0wfyiUDSrNwltooPi0jYaaq0IXlhWDA+JvzUZGRqKg6VZJKdBT4QFCkqhY7ykGg4rzTovfhNxArhXEAx2TnnyHou6HZjFe1KgmqP/xTgi5tzhXFCgzlY6rRefbs24/HWLTIy1YVE8BZzIHzhkVjIg1ig5FEkJggEHbCJ1W+chQpatGrldEFZZ/pfHFYUnj4YxbzroyG3y95UZ9LJiivfgI1EJ+k0OI3EErzr01Vy01ZgR3WjTigedK0kXWPhmIPUh919OhpSlqZegHYV8cHNVh1Rfetw5L+tWliTCgJGW8PGlL1WuGLjwDKNoWKievJoMRCpKFH8=
    on:
      tags: false
      distributions: sdist bdist_wheel
      repo: cloudboss/bossformation
  - provider: pypi
    user: rjosephwright
    password:
      secure: yQ3ipfpMv5OJiW6yRjZcfGA6sRelPK6CTeu5bLhVkp7XNF6gSWNB/Od3ybnWOHcGU9jYvSEF+qPjyHsZoBJQb/M7LUjJjy9xZxUPL3lgwnfHbCzEP6e/UeparYv5lqZvsmXpJHqzESI/DcKDmrTkxIew6i8QczGphPOjZGH1YxV9PB6yOOiAuCkfKG3WQufb7m+6h3QEqcT0Rq2LQgvHl/aBnI8VIPjy5ODpt1QtPYD7mX2vYtyzgc5Jz4MEr5gG8Dub+wZTJBh1KR3Ys9DTVfrtmnwpe2yr8VVokhmODBYY4g1oGkaob1tkkhj3Ke0ZUYASkLDPUPBSo1Y/2Il9Ss/bedQvZcka26OtL9i72rcMdltXbKHioEU4QcF6aTuxlpdRauKvoroUDhDRQsqk8Sh6lGGV9f8HYFNzOfuBqHkWeVwk363QShZA5qIYOjhPq/0oTQx/OJd+G2mlOdD1eqqA9tKlM7bO24ivH6WttQ1vAT7QqoJzoqX9GnvimaxYT2YNyWd3OrslricxbV53Cm5lDUQ/Vpf3eyatELqHkG9JISnjIahpd2p/5HfKUuPu1Fuaxi07UYnMHS/SSgEAHNJQa0i2/T/6w9U0z3Ju7gfBNlabI6gzKPZt98EHgUO3PDlQV8cwa6B46EzIf5IeXeHnouZnyMNoEPciisQXmUQ=
    on:
      tags: true
      distributions: sdist bdist_wheel
      repo: cloudboss/bossformation
